global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "srv3"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'activemq'
    scrape_interval: 5s
#    scheme : https
    scheme : http
    metrics_path: /metrics
    static_configs:
      - targets: ['telegraf:9273']
#    tls_config:
#      insecure_skip_verify: true
#
remote_write:
  - url: "<dashboard url>"
    basic_auth:
      username: "<username>"
      password: "<password>"

