create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
create table merchant (id bigint not null auto_increment, merchant_id varchar(15), name_and_location varchar(99), primary key (id)) engine=InnoDB;
create table merchant_terminals (merchant_id bigint not null, terminals_id bigint not null, primary key (merchant_id, terminals_id)) engine=InnoDB;
create table terminal (id bigint not null auto_increment, terminal_id varchar(8), merchant_id bigint, primary key (id)) engine=InnoDB;
create table transaction_emv_data (id bigint not null auto_increment, application_expiration_date varchar(6), interface_device_serial_number varchar(8), terminal_capabilities tinyblob, primary key (id)) engine=InnoDB;
create table transaction_log (id bigint not null auto_increment, action_code smallint, additional_data varchar(500), amount decimal(19,2) not null, application_transaction_counter varchar(4), authorisation_code varchar(6), card_acceptor_name_and_location varchar(99) not null, card_scheme integer not null, chip_data varchar(512), encrypted_expiry_date varchar(96), encrypted_pan varchar(96) not null, function_code smallint not null, merchant_category_code smallint not null, merchant_id varchar(15) not null, msg_type smallint not null, pan_hash varchar(64) not null, pan_sequence_number smallint not null, point_of_service_data_code varchar(12) not null, proc_code varchar(6) not null, reason_code smallint, stan integer not null, terminal_id varchar(8) not null, transaction_currency_code varchar(3), transaction_date_time varchar(12) not null, utc_capture_date_time datetime not null, transaction_emv_data_id bigint not null, primary key (id)) engine=InnoDB;
alter table merchant add constraint UK_nwmfix3x27256p9mwjjcpo27u unique (merchant_id);
alter table merchant_terminals add constraint UK_axo7yequix355muq966r69m43 unique (terminals_id);
alter table terminal add constraint UK_fhngeu3vlq6brknn700ymodx9 unique (terminal_id);
create index cardSchemeIdx on transaction_log (card_scheme);
create index functionCodeIdx on transaction_log (function_code);
create index utcCaptureDateTimeIdx on transaction_log (utc_capture_date_time);
alter table transaction_log add constraint UniqueMerchantTerminalStan unique (merchant_id, terminal_id, stan);
alter table merchant_terminals add constraint FKdngbc4cyyll3o4ty3kmw615tm foreign key (terminals_id) references terminal (id);
alter table merchant_terminals add constraint FKs94eesvp23fopy73vltsrjfv4 foreign key (merchant_id) references merchant (id);
alter table terminal add constraint FKfjidqcv1fnoe1fvxnhxvw2oxc foreign key (merchant_id) references merchant (id);
alter table transaction_log add constraint FKtb0lwheccb9uailspbkittqha foreign key (transaction_emv_data_id) references transaction_emv_data (id);
